{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "toml-psi",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "toml-psi-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "toml-psi-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 96258,
          "sha1": "fc3b350442cce691f5c8d40cfbe0ad86d902d0a9",
          "md5": "a3e72e67a157bf82d8b2845bce144862"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "parserutil-stub",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "toml-psi-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "toml-psi-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 96258,
          "sha1": "fc3b350442cce691f5c8d40cfbe0ad86d902d0a9",
          "md5": "a3e72e67a157bf82d8b2845bce144862"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "toml-psi-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "toml-psi-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 29013,
          "sha1": "423e2889b1818f201d1c71202564930835093883",
          "md5": "2b9330f8cc8dbcd9f7fd0c48b5fa15ec"
        }
      ]
    }
  ]
}