{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "yaml-psi",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yaml-psi-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "yaml-psi-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 127599,
          "sha1": "8edca2cd11e8c419b79188092125bf85997bb758",
          "md5": "a07ab706c3dccbc77c2056ec3a8d9686"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "parserutil-stub",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.intellij.deps.fastutil",
          "module": "intellij-deps-fastutil",
          "version": {
            "requires": "8.5.18-jb1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "yaml-psi-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "yaml-psi-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 127599,
          "sha1": "8edca2cd11e8c419b79188092125bf85997bb758",
          "md5": "a07ab706c3dccbc77c2056ec3a8d9686"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yaml-psi-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "yaml-psi-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 71573,
          "sha1": "4643caba3d286ecec8d1bcd0b2274ba642970ccd",
          "md5": "fadec8b752987b8fb2271418fd906f49"
        }
      ]
    }
  ]
}