{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-build-info",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amper-build-info-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-build-info-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 2224,
          "sha1": "c3dbd902bab61832779ab8162425a1df3acecd18",
          "md5": "7e7252cde0eb097348b4f416f0cfa57a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-build-info-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-build-info-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 2224,
          "sha1": "c3dbd902bab61832779ab8162425a1df3acecd18",
          "md5": "7e7252cde0eb097348b4f416f0cfa57a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-build-info-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "amper-build-info-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 189,
          "sha1": "3b0198196fc964cb08ad5f80c9d1582bebdc73b3",
          "md5": "0ce7dce0f1f62eb83808a1d508b73d09"
        }
      ]
    }
  ]
}