{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-extensibility-schema-model",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "amper-problem-reporting",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        }
      ],
      "files": [
        {
          "name": "amper-extensibility-schema-model-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-extensibility-schema-model-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 463267,
          "sha1": "b8a62af9c838081b172c283cefcab03cbd2ecb1d",
          "md5": "09736d317a2f98a125e82be9f175d136"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "serialization-extended",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "amper-problem-reporting",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-extensibility-schema-model-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-extensibility-schema-model-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 463267,
          "sha1": "b8a62af9c838081b172c283cefcab03cbd2ecb1d",
          "md5": "09736d317a2f98a125e82be9f175d136"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-extensibility-schema-model-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "amper-extensibility-schema-model-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 10173,
          "sha1": "20c6e0e1b9386ef5ac7f65d4f7985ea367671663",
          "md5": "094c9cf67405cdfe1f04870590bf70c8"
        }
      ]
    }
  ]
}