{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-problem-reporting",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amper-problem-reporting-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-problem-reporting-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 25287,
          "sha1": "78e93a8b6d6e8e7db58ff66a79dc90fef331d5ae",
          "md5": "4189cf0ff175543d1017398643a4e93d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.1.0"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "stdlib-extended",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-problem-reporting-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-problem-reporting-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 25287,
          "sha1": "78e93a8b6d6e8e7db58ff66a79dc90fef331d5ae",
          "md5": "4189cf0ff175543d1017398643a4e93d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-problem-reporting-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "amper-problem-reporting-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 7457,
          "sha1": "c6af80785dc65d4e3029f6d18b060a582a8cec4b",
          "md5": "c5cd19f9c1a7b21b482d94f0f19388b5"
        }
      ]
    }
  ]
}