{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "parserutil-stub",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jetbrains.intellij.platform",
          "module": "core-impl",
          "version": {
            "requires": "261.26222.65"
          }
        },
        {
          "group": "com.jetbrains.intellij.platform",
          "module": "core",
          "version": {
            "requires": "261.26222.65"
          }
        },
        {
          "group": "com.jetbrains.intellij.platform",
          "module": "util",
          "version": {
            "requires": "261.26222.65"
          }
        },
        {
          "group": "com.jetbrains.intellij.platform",
          "module": "util-ex",
          "version": {
            "requires": "261.26222.65"
          }
        }
      ],
      "files": [
        {
          "name": "parserutil-stub-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "parserutil-stub-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 31424,
          "sha1": "09794e2a111d9e2d04cfdc69a90e7f33e9e711f9",
          "md5": "c3b3deaab6cd872b4c4d3981e4e8ece0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jetbrains.intellij.platform",
          "module": "core-impl",
          "version": {
            "requires": "261.26222.65"
          }
        },
        {
          "group": "com.jetbrains.intellij.platform",
          "module": "core",
          "version": {
            "requires": "261.26222.65"
          }
        },
        {
          "group": "com.jetbrains.intellij.platform",
          "module": "util",
          "version": {
            "requires": "261.26222.65"
          }
        },
        {
          "group": "com.jetbrains.intellij.platform",
          "module": "util-ex",
          "version": {
            "requires": "261.26222.65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "parserutil-stub-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "parserutil-stub-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 31424,
          "sha1": "09794e2a111d9e2d04cfdc69a90e7f33e9e711f9",
          "md5": "c3b3deaab6cd872b4c4d3981e4e8ece0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parserutil-stub-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "parserutil-stub-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 12167,
          "sha1": "74c35250be901566743f052867ddad3e1911eeec",
          "md5": "ccc1120ac6cb6593625eb464fd722085"
        }
      ]
    }
  ]
}