{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "maven-central-configuration",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "maven-central-configuration-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "maven-central-configuration-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 2597,
          "sha1": "e492b2802d3074c5f155bb6953aea93b82780f77",
          "md5": "18909935621ef6894341a56b3c2c2bab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "maven-central-configuration-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "maven-central-configuration-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 2597,
          "sha1": "e492b2802d3074c5f155bb6953aea93b82780f77",
          "md5": "18909935621ef6894341a56b3c2c2bab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maven-central-configuration-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "maven-central-configuration-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 1571,
          "sha1": "212790e715c3efe1506b439af98a5fa8fa8998a5",
          "md5": "3701a90c07c815c64b63d30e6fb7f9bf"
        }
      ]
    }
  ]
}