{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "jetbrains-jdk-list",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jetbrains-jdk-list-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "jetbrains-jdk-list-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 31258,
          "sha1": "a28a3a812bfd4a854733a9c1207aad02699675a1",
          "md5": "5d61f0cc2c1319b8b86402f5d28f1a6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "jetbrains-jdk-list-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "jetbrains-jdk-list-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 31258,
          "sha1": "a28a3a812bfd4a854733a9c1207aad02699675a1",
          "md5": "5d61f0cc2c1319b8b86402f5d28f1a6e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jetbrains-jdk-list-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "jetbrains-jdk-list-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 1910,
          "sha1": "12f5181be71c26bfd6cc499699b8721fb1fe0059",
          "md5": "4f785cc207a3830f6f01d95c375f3b68"
        }
      ]
    }
  ]
}