{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "incremental-cache",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "telemetry",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        }
      ],
      "files": [
        {
          "name": "incremental-cache-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "incremental-cache-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 124026,
          "sha1": "34744edc9d5438dda651ffdb52cff9a51377a523",
          "md5": "feb305517137fdb0f5a536d244eaa9e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "concurrency",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "nio-filechannels",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "telemetry",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "incremental-cache-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "incremental-cache-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 124026,
          "sha1": "34744edc9d5438dda651ffdb52cff9a51377a523",
          "md5": "feb305517137fdb0f5a536d244eaa9e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "incremental-cache-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "incremental-cache-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 15543,
          "sha1": "2c40e607424d0d7b9f08295e96be525a5d2d90bf",
          "md5": "c77063459130ea27b28e1d4d2a373d6c"
        }
      ]
    }
  ]
}