{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "concurrency",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "concurrency-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "concurrency-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 54541,
          "sha1": "39e51df54630306266a4e18815d9b50b0ef93aeb",
          "md5": "3ebf85b5cc15239b61e912b012f884c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "concurrency-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "concurrency-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 54541,
          "sha1": "39e51df54630306266a4e18815d9b50b0ef93aeb",
          "md5": "3ebf85b5cc15239b61e912b012f884c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "concurrency-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "concurrency-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 11202,
          "sha1": "efbee8fe706886057f19148e9db8b77cdffdd7f1",
          "md5": "f9f46c27bb8cb2d305814b59787295d8"
        }
      ]
    }
  ]
}