{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "serialization-extended",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "serialization-extended-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "serialization-extended-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 3429,
          "sha1": "b6e0f6faae39e9f4aab2b71b6637d7b7e7ce77b7",
          "md5": "0f505b481356cc660cfa41057e3a2f8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "serialization-extended-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "serialization-extended-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 3429,
          "sha1": "b6e0f6faae39e9f4aab2b71b6637d7b7e7ce77b7",
          "md5": "0f505b481356cc660cfa41057e3a2f8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "serialization-extended-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "serialization-extended-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 1781,
          "sha1": "6d6b41490718f6d6db100721b2d978b440311ceb",
          "md5": "e502136fcdf44e6bf7b07b936ad1a5d2"
        }
      ]
    }
  ]
}