{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "system-info",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "system-info-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "system-info-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 12819,
          "sha1": "4e1fdc55f1804740f55a489064f5d5cf5d6167ff",
          "md5": "9c7b404c20dbb7412836d492588ee8df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "system-info-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "system-info-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 12819,
          "sha1": "4e1fdc55f1804740f55a489064f5d5cf5d6167ff",
          "md5": "9c7b404c20dbb7412836d492588ee8df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "system-info-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "system-info-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 2911,
          "sha1": "9d176c0769d800a9482dc363cc125ac68a6b22eb",
          "md5": "7dc07a444a168be9f5bc7ae0d91127cf"
        }
      ]
    }
  ]
}