{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "frontend-api",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "core",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "amper-extensibility-schema-model",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        }
      ],
      "files": [
        {
          "name": "frontend-api-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "frontend-api-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 646673,
          "sha1": "0d4bc920b7a482ce4554b1ea729efd7d0de1e2cb",
          "md5": "fc8415b73816a04703099a9f56153f92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "amper-build-info",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "amper-problem-reporting",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "core",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "amper-extensibility-schema-model",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "stdlib-extended",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "amper-swift-pm-resolution-model",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "com.jetbrains.intellij.platform",
          "module": "core",
          "version": {
            "requires": "261.26222.65"
          }
        },
        {
          "group": "com.jetbrains.intellij.platform",
          "module": "util",
          "version": {
            "requires": "261.26222.65"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "frontend-api-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "frontend-api-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 646673,
          "sha1": "0d4bc920b7a482ce4554b1ea729efd7d0de1e2cb",
          "md5": "fc8415b73816a04703099a9f56153f92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "frontend-api-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "frontend-api-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 106074,
          "sha1": "deadd082207177a33c5f6d7a94cae79809bd66ce",
          "md5": "09f4a765b9d945d0a881cfdb50c9730b"
        }
      ]
    }
  ]
}