{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-events",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amper-events-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-events-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 122988,
          "sha1": "1b43121f00ce69732b97f9c8253a1aecbae44e85",
          "md5": "41b8974e271978ffff8fb7d0c7849509"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-events-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-events-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 122988,
          "sha1": "1b43121f00ce69732b97f9c8253a1aecbae44e85",
          "md5": "41b8974e271978ffff8fb7d0c7849509"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-events-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "amper-events-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 9207,
          "sha1": "758ba5d2a6311c532ae0a7db79dad8b07fab2e13",
          "md5": "fb9ec89bab6b275c86bbbc165e7a22fd"
        }
      ]
    }
  ]
}