{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-schema-processing",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "amper-extensibility-schema-model",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "analysis-api-for-ide",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "amper-schema-processing-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-schema-processing-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 140707,
          "sha1": "1365f59feca9259be9b2525227df63aa7810317c",
          "md5": "1f5e2fdc94d2302090b54296b79a75ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "amper-extensibility-schema-model",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "stdlib-extended",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "analysis-api-for-ide",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "analysis-api-impl-base-for-ide",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "analysis-api-k2-for-ide",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "low-level-api-fir-for-ide",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "analysis-api-platform-interface-for-ide",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "symbol-light-classes-for-ide",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-schema-processing-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-schema-processing-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 140707,
          "sha1": "1365f59feca9259be9b2525227df63aa7810317c",
          "md5": "1f5e2fdc94d2302090b54296b79a75ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-schema-processing-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "amper-schema-processing-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 19042,
          "sha1": "0fe085eb064b1f18a0b95544a93e22f758e0ff55",
          "md5": "c14dd3ecf99a02adc5ca607e65e0c134"
        }
      ]
    }
  ]
}