{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "maven-plugin-xml-parser",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "maven-plugin-xml-parser-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "maven-plugin-xml-parser-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 77495,
          "sha1": "a9465d9291a8c0a3835eb21db6b79bc1619eb59c",
          "md5": "6507ceb1be87c6f6c18b1f2651458a25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization-jvm",
          "version": {
            "requires": "0.86.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "maven-plugin-xml-parser-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "maven-plugin-xml-parser-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 77495,
          "sha1": "a9465d9291a8c0a3835eb21db6b79bc1619eb59c",
          "md5": "6507ceb1be87c6f6c18b1f2651458a25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maven-plugin-xml-parser-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "maven-plugin-xml-parser-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 3004,
          "sha1": "ac3db60530725bd629310559188fa57fb5547621",
          "md5": "96edda4f01fc69ff936c29b285cb6656"
        }
      ]
    }
  ]
}