{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-kotlin-native",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "kotlin-native-rules",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        }
      ],
      "files": [
        {
          "name": "amper-kotlin-native-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-kotlin-native-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 10814,
          "sha1": "346c9d139a30fabc6ac623df1a1e2b71d3d91917",
          "md5": "6b80ed2116aa9f29ced8d611de6738f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "core",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "frontend-api",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "kotlin-native-rules",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "maven-central-configuration",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "system-info",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-kotlin-native-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-kotlin-native-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 10814,
          "sha1": "346c9d139a30fabc6ac623df1a1e2b71d3d91917",
          "md5": "6b80ed2116aa9f29ced8d611de6738f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-kotlin-native-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "amper-kotlin-native-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 3096,
          "sha1": "9b611b7e74ee40a7ced9e4884aaa7f9d7bac74ed",
          "md5": "fdad7fba94d5f92d6670f6be833254dc"
        }
      ]
    }
  ]
}