{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-test-events",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "amper-events",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        }
      ],
      "files": [
        {
          "name": "amper-test-events-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-test-events-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 128739,
          "sha1": "ba85bbd36d3499f7bbd3f7666e15f7db53f4c3c0",
          "md5": "9d7a677a85466d1052e2ffe80d68e53e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "amper-events",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "serialization-extended",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-test-events-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-test-events-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 128739,
          "sha1": "ba85bbd36d3499f7bbd3f7666e15f7db53f4c3c0",
          "md5": "9d7a677a85466d1052e2ffe80d68e53e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-test-events-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "amper-test-events-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 2507,
          "sha1": "8deca9bbecb3d386926ff7ebb306015e88c6ac70",
          "md5": "88ece7d5254e5854e5b03422924af566"
        }
      ]
    }
  ]
}