{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-telemetry",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amper-telemetry-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-telemetry-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 19904,
          "sha1": "c8a3c898c88e27e5ba17f8ecd1a11f2e14abbfef",
          "md5": "7226dac9da94cc45e5244e1c4d179c98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "amper-build-info",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "telemetry",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-common",
          "version": {
            "requires": "1.60.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-logging-otlp",
          "version": {
            "requires": "1.60.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-trace",
          "version": {
            "requires": "1.60.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.60.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-telemetry-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-telemetry-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 19904,
          "sha1": "c8a3c898c88e27e5ba17f8ecd1a11f2e14abbfef",
          "md5": "7226dac9da94cc45e5244e1c4d179c98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-telemetry-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "amper-telemetry-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 4617,
          "sha1": "1990090f71e1917be7e43d66593113ae62939c43",
          "md5": "3817d5e9f0c9fea2b6a2afa08a1cfd7a"
        }
      ]
    }
  ]
}