{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-extensibility-schema-model",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "amper-problem-reporting",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        }
      ],
      "files": [
        {
          "name": "amper-extensibility-schema-model-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-extensibility-schema-model-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 463267,
          "sha1": "226e918c300381bae29ca4763068631759283696",
          "md5": "15a42fc342a8500e25214cd07d71eefe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "serialization-extended",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "amper-problem-reporting",
          "version": {
            "requires": "0.12.0-dev-4300-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-extensibility-schema-model-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "amper-extensibility-schema-model-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 463267,
          "sha1": "226e918c300381bae29ca4763068631759283696",
          "md5": "15a42fc342a8500e25214cd07d71eefe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-extensibility-schema-model-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "amper-extensibility-schema-model-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 10173,
          "sha1": "507cfa53640aa569c54e71153f79a04323df3a39",
          "md5": "faff892fa504cfbd748ea83615a1e9b6"
        }
      ]
    }
  ]
}