{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "serialization-extended",
    "version": "0.12.0-dev-4300-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "serialization-extended-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "serialization-extended-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 3429,
          "sha1": "e37acc3faf1cd8e42f6d28f2bec979a46df05277",
          "md5": "d450b4506398e30b8b9c065f48eea8af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "serialization-extended-0.12.0-dev-4300-fork-kof-1.jar",
          "url": "serialization-extended-0.12.0-dev-4300-fork-kof-1.jar",
          "size": 3429,
          "sha1": "e37acc3faf1cd8e42f6d28f2bec979a46df05277",
          "md5": "d450b4506398e30b8b9c065f48eea8af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "serialization-extended-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "url": "serialization-extended-0.12.0-dev-4300-fork-kof-1-sources.jar",
          "size": 1781,
          "sha1": "463a196bf75a06c26004ce17b001fdec268e21c3",
          "md5": "4a5db4b6d02e1ffab3f7e5d1eb7d8b7f"
        }
      ]
    }
  ]
}