{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-swift-pm-resolution-model",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amper-swift-pm-resolution-model-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-swift-pm-resolution-model-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 112191,
          "sha1": "5e6333a71cc44e6d24f8a8af6040462a9503ba38",
          "md5": "bfbaddb2b425f53b5f6094308cc90772"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "serialization-extended",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-swift-pm-resolution-model-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-swift-pm-resolution-model-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 112191,
          "sha1": "5e6333a71cc44e6d24f8a8af6040462a9503ba38",
          "md5": "bfbaddb2b425f53b5f6094308cc90772"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-swift-pm-resolution-model-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "amper-swift-pm-resolution-model-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 4145,
          "sha1": "82c2c5e51501bc03aeb76e689eddca876df71404",
          "md5": "a24b06982651cec518144a2798dcb158"
        }
      ]
    }
  ]
}