{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-project-template-resources",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amper-project-template-resources-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-project-template-resources-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 13162,
          "sha1": "1160f253b389246dfd6399edce5d3fa17d3138f3",
          "md5": "fa22705502a55c026a49415e309ece9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-project-template-resources-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-project-template-resources-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 13162,
          "sha1": "1160f253b389246dfd6399edce5d3fa17d3138f3",
          "md5": "fa22705502a55c026a49415e309ece9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-project-template-resources-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "amper-project-template-resources-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 1484,
          "sha1": "871b0831955c938296c2234742e59e2a370c248b",
          "md5": "093571adc0b2d41211b7e362eb83d9de"
        }
      ]
    }
  ]
}