{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "maven-plugin-xml-parser",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "maven-plugin-xml-parser-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "maven-plugin-xml-parser-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 77495,
          "sha1": "8ef5cb9287b146ee44750eee1195801035971d60",
          "md5": "a823ecaf3db19906016742459ca4b902"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization-jvm",
          "version": {
            "requires": "0.86.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "maven-plugin-xml-parser-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "maven-plugin-xml-parser-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 77495,
          "sha1": "8ef5cb9287b146ee44750eee1195801035971d60",
          "md5": "a823ecaf3db19906016742459ca4b902"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maven-plugin-xml-parser-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "maven-plugin-xml-parser-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 3004,
          "sha1": "59d9965a6e3266b886d26a143fa6585df4e23cf0",
          "md5": "3a20efbe61012a37dfdb8915f7706289"
        }
      ]
    }
  ]
}