{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.amper",
    "module": "amper-wrapper",
    "version": "0.13.0-dev-4307-fork-kof-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "kotlinToolchain": {
      "version": "0.12.0-dev-4289"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amper-wrapper-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-wrapper-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 37497,
          "sha1": "b91cb23c5da0b5d88098ff7d1d1e28b609a80bf2",
          "md5": "3249b0586dab14621e9dc0f02feae782"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.amper",
          "module": "core",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "system-info",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.jetbrains.amper",
          "module": "stdlib-extended",
          "version": {
            "requires": "0.13.0-dev-4307-fork-kof-1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "amper-wrapper-0.13.0-dev-4307-fork-kof-1.jar",
          "url": "amper-wrapper-0.13.0-dev-4307-fork-kof-1.jar",
          "size": 37497,
          "sha1": "b91cb23c5da0b5d88098ff7d1d1e28b609a80bf2",
          "md5": "3249b0586dab14621e9dc0f02feae782"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amper-wrapper-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "url": "amper-wrapper-0.13.0-dev-4307-fork-kof-1-sources.jar",
          "size": 4590,
          "sha1": "94319a90e56e7509f30ce2eebc5f831b83b00eb8",
          "md5": "897c9259121ef0329e897eb31423fc3d"
        }
      ]
    }
  ]
}